version: '2'
services:
  web:
    container_name: web.1
    image: ideato/nginx-phpfpm:5.6
    volumes:
      - /mnt/docker/htdocs/example1.it:/var/www/vhosts/example1.it
      - /mnt/docker/confs/nginx/vhosts/example1.conf:/etc/nginx/conf.d/default.conf
      - /mnt/docker/confs/phpfpm:/etc/php-fpm.d/
      - /mnt/docker/confs/phpfpm/php.ini:/etc/php.ini
    ports:
      - "80:8081"
    links:
      - database

  database:
    container_name: mysql.1
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'