web.1:
  container_name: web.1
  image: ideato/nginx-phpfpm:5.6
  volumes:
    - /mnt/docker/htdocs/example1.it:/var/www/vhosts/example1.it
    - /mnt/docker/confs/nginx/vhosts/example1.conf:/etc/nginx/conf.d/default.conf
    - /mnt/docker/confs/phpfpm:/etc/php-fpm.d/
    - /mnt/docker/confs/phpfpm/php.ini:/etc/php.ini
  ports:
    - "80:8081"
  links:
    - db.1
    - es.1
db.1:
  container_name: db.1
  image: mysql:5.6
  volumes:
    - /var/lib/mysql.1:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
es.1:
  container_name: es.1
  image: elasticsearch:1.7.5
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"